server:
  port: 9007

spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        #默认是8719端口，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-provider-payment




#本来可以直接使用ribbon.ConnectTimeOut 和ribbon.ReadTimeOut来设置超时时间的，可能是ribbon依赖冲突
feign:
  sentinel:
    enabled: true #激活sentinel对feign的支持
  client:
    config:
      default:
        #建立连接所用时间，适用于网络正常的情况下，两端连接所用时间
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 5000

#配置feign日志级别
logging:
  #feign以什么级别监控哪个接口
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
