server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka



#本来可以直接使用ribbon.ConnectTimeOut 和ribbon.ReadTimeOut来设置超时时间的，可能是ribbon依赖冲突
feign:
  client:
    config:
      default:
        #建立连接所用时间，适用于网络正常的情况下，两端连接所用时间
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 5000

#配置feign日志级别
logging:
  #feign以什么级别监控哪个接口
  level:
   com.atguigu.springcloud.service.PaymentFeignService: debug
